version: "3"

services:
  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changethispassword}
    volumes:
      - mysql:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/

  serviceregistry:
    container_name: serviceregistry
    ports:
      - 8443:8443
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-serviceregistry-4.6.0/:/opt/arrowhead/
      - ./certs/serviceregistry.p12:/opt/arrowhead/certificates/serviceregistry.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12
    command: java -jar arrowhead-serviceregistry-4.6.0.jar

  authorization:
    container_name: authorization
    ports:
      - 8445:8445
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-authorization-4.6.0/:/opt/arrowhead/
      - ./certs/authorization.p12:/opt/arrowhead/certificates/authorization.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12
    command: java -jar arrowhead-authorization-4.6.0.jar

  orchestrator:
    container_name: orchestrator
    ports:
      - 8441:8441
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-orchestrator-4.6.0/:/opt/arrowhead/
      - ./certs/orchestrator.p12:/opt/arrowhead/certificates/orchestrator.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12
    command: java -jar arrowhead-orchestrator-4.6.0.jar

  certificateauthority:
    container_name: certificateauthority
    ports:
      - 8448:8448
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-certificate-authority-4.6.0/:/opt/arrowhead/
      - ./certs/certificateauthority.p12:/opt/arrowhead/certificates/certificateauthority.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12
      - ./certs/cloud/:/opt/arrowhead/certificates/cloud/
    command: java -jar arrowhead-certificate-authority-4.6.0.jar

  gatekeeper:
    container_name: gatekeeper
    ports:
      - 8449:8449
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-gatekeeper-4.6.0/:/opt/arrowhead/
      - ./certs/gatekeeper.p12:/opt/arrowhead/certificates/gatekeeper.p12
      - ./certs/gk_gw_truststore.p12:/opt/arrowhead/certificates/truststore.p12
    command: java -jar arrowhead-gatekeeper-4.6.0.jar

  gateway:
    container_name: gateway
    ports:
      - 8453:8453
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-gateway-4.6.0/:/opt/arrowhead/
      - ./certs/gateway.p12:/opt/arrowhead/certificates/gateway.p12
      - ./certs/gk_gw_truststore.p12:/opt/arrowhead/certificates/truststore.p12
    command: java -jar arrowhead-gateway-4.6.0.jar

  eventhandler:
    container_name: eventhandler
    ports:
      - 8455:8455
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-eventhandler-4.6.0/:/opt/arrowhead/
      - ./certs/eventhandler.p12:/opt/arrowhead/certificates/eventhandler.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12
    command: java -jar arrowhead-eventhandler-4.6.0.jar

volumes:
  mysql:
