version: "3"

services:
  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changethispassword}
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/

  serviceregistry:
    container_name: serviceregistry
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8443:8443
    volumes:
      - ./services/arrowhead-serviceregistry-4.6.0/arrowhead-serviceregistry-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-serviceregistry-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-serviceregistry-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/serviceregistry.p12:/opt/arrowhead/certificates/serviceregistry.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12

  authorization:
    container_name: authorization
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8445:8445
    image: openjdk:11-jre-slim
    working_dir: /opt/arrowhead
    volumes:
      - ./services/arrowhead-authorization-4.6.0/arrowhead-authorization-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-authorization-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-authorization-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/authorization.p12:/opt/arrowhead/certificates/authorization.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12

  orchestrator:
    container_name: orchestrator
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8441:8441
    volumes:
      - ./services/arrowhead-orchestrator-4.6.0/arrowhead-orchestrator-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-orchestrator-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-orchestrator-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/orchestrator.p12:/opt/arrowhead/certificates/orchestrator.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12

  certificateauthority:
    container_name: certificateauthority
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8448:8448
    volumes:
      - ./services/arrowhead-certificate-authority-4.6.0/arrowhead-certificate-authority-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-certificate-authority-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-certificate-authority-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/certificateauthority.p12:/opt/arrowhead/certificates/certificateauthority.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12
      - ./certs/cloud:/opt/arrowhead/certificates/cloud

  gatekeeper:
    container_name: gatekeeper
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8449:8449
    volumes:
      - ./services/arrowhead-gatekeeper-4.6.0/arrowhead-gatekeeper-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-gatekeeper-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-gatekeeper-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/gatekeeper.p12:/opt/arrowhead/certificates/gatekeeper.p12
      - ./certs/gk_gw_truststore.p12:/opt/arrowhead/certificates/truststore.p12

  gateway:
    container_name: gateway
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8453:8453
    volumes:
      - ./services/arrowhead-gateway-4.6.0/arrowhead-gateway-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-gateway-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-gateway-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/gateway.p12:/opt/arrowhead/certificates/gateway.p12
      - ./certs/gk_gw_truststore.p12:/opt/arrowhead/certificates/truststore.p12

  eventhandler:
    container_name: eventhandler
    extends:
      file: arrowhead-common.yml
      service: arrowhead-service
    ports:
      - 8455:8455
    volumes:
      - ./services/arrowhead-eventhandler-4.6.0/arrowhead-eventhandler-4.6.0.jar:/opt/arrowhead/app.jar
      - ./services/arrowhead-eventhandler-4.6.0/application.properties:/opt/arrowhead/application.properties
      - ./services/arrowhead-eventhandler-4.6.0/log4j2.xml:/opt/arrowhead/log4j2.xml
      - ./certs/eventhandler.p12:/opt/arrowhead/certificates/eventhandler.p12
      - ./certs/truststore.p12:/opt/arrowhead/certificates/truststore.p12

volumes:
  mysql:
